apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-addons
spec:
  project: default
  source:
    repoURL: https://github.com/grv180290/argo-eks-addons.git
    targetRevision: HEAD
    path: 'chart/templates/metrics-server.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
